project:
  name: stock-volatility-prediction
  timezone: America/New_York
  seed: 42

universe:
  tickers: ["Apple", "Amazon"]
  ticker_symbols: ["PNC", "NEM", "AEP", "BJ", "APH", "ADP"]
  start_date_news: "2025-03-18" # Train window begin exclusive for news
  start_date: "2026-02-10"      # Train window begin
  end_date: "2026-04-16"        # Train window end
  target_date: "2026-04-17"     # Target date for prediction

frequency:
  base: "1D"               # daily base timeline
  market_close_time: "16:00:00"

output:
  processed_dir: "data/processed"
  artifacts_dir: "artifacts"
  overwrite: false

keyword_count: 5          # number of keywords per ticker
llm_run_count: 1          # number of times to run the llm

peer_count: 6              # number of peer companies per base ticker
news_limit_per_ticker: 10000 # max news articles per ticker (Yahoo and Finnhub)

prediction_ratio: 0.1  # The ratio of importance of social (close to 0) vs news (close to 1) prediction in final prediction

day_weights: [1, 0.5, 0.33, 0.2, 0.1]
feature_weights: [
  1,  # 0  num_posts
  1,  # 1  log_impressions
  .1,  # 2  mean_compound
  .1,  # 3  impression_weighted_compound
  .1,  # 4  mean_pos
  .1,  # 5  mean_neg
  .1,  # 6  mean_neu
  .1,  # 7  pos_neg_ratio
  .1,  # 8  sentiment_balance
  .1,  # 9  bullish_ratio
  .1,  # 10 bearish_ratio
  1,  # 11 variance_compound
  1,  # 12 std_compound
  .1,  # 13 term_diversity
  .1,  # 14 top_term_ratio
  3,  # 15 volatility (lagged)
]

feature_weights_news: [
  1,  # 0  num_posts
  .1,  # 1  mean_compound
  .1,  # 2  mean_pos
  .1,  # 3  mean_neg
  .1,  # 4  mean_neu
  .1,  # 5  pos_neg_ratio
  .1,  # 6  sentiment_balance
  .1,  # 7  bullish_ratio
  .1,  # 8 bearish_ratio
  1,  # 9 variance_compound
  1,  # 10 std_compound
  2,  # 11 volatility (lagged)
]